In [1]:
import pandas as pd
import numpy as np
import func_rna as func

In [2]:
colnames = list(map(str, range(1, 31)))
colnames.insert(0, 'Diagnosis')
breast_cancer = pd.read_csv('wdbc.data', index_col=0, names = colnames, header = None)
heart = pd.read_csv('heart.dat', header = None, delim_whitespace=True)

In [3]:
def sub_diagnosis(diagnosis):
    if diagnosis == 'B':
        return -1
    else:
        return 1
    
breast_cancer.Diagnosis = breast_cancer.Diagnosis.apply(sub_diagnosis) 
breast_cancer_x = breast_cancer.iloc[:,1:31]
breast_cancer_x = (breast_cancer_x-breast_cancer_x.min())/(breast_cancer_x.max()-breast_cancer_x.min())
breast_cancer.iloc[:,1:31] = breast_cancer_x

In [4]:
def sub_diagnosis_heart(diagnosis):
    if diagnosis == 2:
        return -1
    else:
        return 1
heart.iloc[:,13] = heart.iloc[:,13].apply(sub_diagnosis_heart) 
heart_x = heart.iloc[:,0:13]
heart_x = (heart_x-heart_x.min())/(heart_x.max()-heart_x.min())
heart.iloc[:,0:13] = heart_x

In [111]:
breast_cancer.head()

,Diagnosis,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
842302,1,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,0.686364,...,0.620776,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864
842517,1,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,0.379798,...,0.606901,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878
84300903,1,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,0.509596,...,0.556386,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433
84348301,1,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,0.776263,...,0.248310,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711
84358402,1,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,0.378283,...,0.519744,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595

In [108]:
heart.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.854167,1.0,1.000000,0.339623,0.447489,0.0,1.0,0.290076,0.0,0.387097,0.5,1.000000,0.0,-1
1,0.791667,0.0,0.666667,0.198113,1.000000,0.0,1.0,0.679389,0.0,0.258065,0.5,0.000000,1.0,1
2,0.583333,1.0,0.333333,0.283019,0.308219,0.0,0.0,0.534351,0.0,0.048387,0.0,0.000000,1.0,-1
3,0.729167,1.0,1.000000,0.320755,0.312785,0.0,0.0,0.259542,1.0,0.032258,0.5,0.333333,1.0,1
4,0.937500,0.0,0.333333,0.245283,0.326484,0.0,1.0,0.381679,1.0,0.032258,0.0,0.333333,0.0,1

In [7]:
X_cancer = breast_cancer.iloc[:,1:31].to_numpy()
y_cancer = breast_cancer.Diagnosis.to_numpy().reshape((-1,1))

X_heart = heart.iloc[:,0:13].to_numpy()
y_heart = heart.iloc[:,13].to_numpy().reshape((-1,1))

print(f'X Cancer Shape: {X_cancer.shape}\nY Cancer shape: {y_cancer.shape}')
print(f'X Cancer Shape: {X_heart.shape}\nY Cancer shape: {y_heart.shape}')

X Cancer Shape: (569, 30)
Y Cancer shape: (569, 1)
X Cancer Shape: (270, 13)
Y Cancer shape: (270, 1)

In [8]:
from sklearn.model_selection import train_test_split as tts
X_cancer_train, X_cancer_test, y_cancer_train, y_cancer_test = tts(X_cancer, y_cancer, test_size=0.3)
X_heart_train, X_heart_test, y_heart_train, y_heart_test = tts(X_heart, y_heart, test_size=0.3)

print(f'X Cancer Training Shape: {X_cancer_train.shape}\nY Cancer Training shape: {y_cancer_train.shape}\nX Cancer Testing Shape: {X_cancer_test.shape}\nY Cancer Testing Shape: {y_cancer_test.shape}')
print(f'\n\nX Heart Training Shape: {X_heart_train.shape}\nY Heart Training shape: {y_heart_train.shape}\nX Heart Testing Shape: {X_heart_test.shape}\nY Heart Testing Shape: {y_heart_test.shape}')

X Cancer Training Shape: (398, 30)
Y Cancer Training shape: (398, 1)
X Cancer Testing Shape: (171, 30)
Y Cancer Testing Shape: (171, 1)


X Heart Training Shape: (189, 13)
Y Heart Training shape: (189, 1)
X Heart Testing Shape: (81, 13)
Y Heart Testing Shape: (81, 1)

In [88]:
W_cancer, H_cancer, Z_cancer = func.ELM_train(X_cancer_train, y_cancer_train, 10)
y_h_cancer = func.ELM_y(X_cancer_test, W_cancer, Z_cancer)
accuracy = (y_h_cancer == y_cancer_test).mean()
print(accuracy)

0.07602339181286549

In [103]:
W_heart, H_heart, Z_heart = func.ELM_train(X_heart_train, y_heart_train, 200)
y_h_heart = func.ELM_y(X_heart_test, W_heart, Z_heart)
accuracy = (y_h_heart == y_heart_test).mean()
print(accuracy)

0.38271604938271603